version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: wordpress_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    # Optional: Expose port for database management (e.g., with phpMyAdmin)
    # ports:
    #   - "3306:3306"
    networks:
      - wordpress-net

  wordpress:
    image: wordpress:latest
    container_name: wordpress_site
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wp_data:/var/www/html
    ports:
      - "8080:80"
    restart: always
    networks:
      - wordpress-net
    depends_on:
      - db

volumes:
  db_data:
  wp_data:

networks:
  wordpress-net:
    driver: bridge

